version: '3'
services: 
  express-app:
    build: .
    ports:
      - '3000:3000'
    # depends_on:
    #   - db
    environment:
      DATABASE_URL: "postgresql://postgres:123@localhost:5432/mydb?schema=public"
  # db:
  #   image: postgres:13
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USERNAME: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: mydb